### ISSUE TITLE
Sails lift fails: Warning: Task "typescript" not found. 

### ISSUE THREAD

**Issue by waltercolindres** [erikschlegel/sails-generate-reactjs#3]
New install. Everything seems to be working correctly outside of this error.

I've run:
sudo chown -R 501 /Users/XXXXDesktop/XXXX/.tmp

Still won't run.

**Comment by erikschlegel** [comment]
Apologies for the delay. Can you send me over the full error message you see from grunt when you try to re-lift the site? Unfortunately, I'm unable to reproduce the error from my end.

Thanks.

Erik

**Comment by waltercolindres** [comment]
# XXXXX at Walters-MacBook-Pro.local in ~/Desktop/XXXX [10:11:48]

$ sails lift 

info: Starting app...

info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.0             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---**_--**_---**_--**_---**_--**_
info:  ____---**_--**_---**_--**_---**_--**_-__
info: 
info: Server lifted in `/Users/XXXXX/Desktop/XXXXXX`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Wed Jun 17 2015 10:12:00 GMT-0500 (CDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
error: *\* Grunt :: An error occurred. **

## error: 

Aborted due to warnings.
Running "mochaTest:test" (mochaTest) task

  Array
    #indexOf()
      ✓ should return -1 when the value is not present

  1 passing (3ms)

## Warning: Task "typescript" not found. 

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error: 
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error: 
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error: 
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/Users/XXXX/Desktop/XXXX/.tmp` ?
error: 
error:      If you think this might be the case, try running:
error:      sudo chown -R 501 /Users/XXXXX/Desktop/XXXXX/.tmp

**Comment by waltercolindres** [comment]
Think I found my issue:
Bower Install finished
error: Couldn't move bower_components folder to /Users/XXXXX/Desktop/fresh/punchlist/assets/vendor, try running `bower install`.

**Comment by waltercolindres** [comment]
Also, my app/main & app/components ts/es6 folders are empty after creating the project.

**Comment by waltercolindres** [comment]
Ok, so looks like I am having a permissions issue.
