### ISSUE TITLE
Warning: Task "typescript" not found.

### ISSUE THREAD

**Issue by mtbvang** [erikschlegel/sails-generate-reactjs#5]
Followed the installation instructions and got the warning when doing `sails lift` because there is a reference to a typescript task in tasks/register/compileAssets.js line 9. Commenting out this task dependency the applications lifts fine.

**Comment by mattcodez** [comment]
The typescript.js file is completely missing from `tasks/config`, so I added the file manually from here https://github.com/erikschlegel/sails-generate-reactjs/blob/master/templates/tasks/config/typescript.js
Seemed to take care of the issue.

I think the typescript.js file just needs a reference in here https://github.com/erikschlegel/sails-generate-reactjs/blob/master/lib/index.js
